yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'


urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),

]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),

]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),

]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import UniqueConstraint

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField('Текст', help_text='Начните вводить текст здесь')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу или оставьте поле пустым'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий'
    )
    author = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(help_text='Оставьте комментарий')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписка'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            UniqueConstraint(fields=['user', 'author'], name='follow_unique')
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from yatube.settings import PAGE_COEF

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


# Вынес paginator  в отдельную функцию
def pagination(request, object, coef):
    paginator = Paginator(object, coef)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


# Главная страница

def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.all()
    page_obj = pagination(request, post_list, PAGE_COEF)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


# Посты по группам

def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = pagination(request, posts, PAGE_COEF)
    context = {
        'page_obj': page_obj,
        'group': group
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    post_count = post_list.count()
    user = request.user
    page_obj = pagination(request, post_list, PAGE_COEF)
    if user.is_authenticated and author.following.filter(user=user).exists():
        following = True
    else:
        following = False
    followers_count = author.following.count()
    context = {
        'post_count': post_count,
        'author': author,
        'page_obj': page_obj,
        'following': following,
        'followers_count': followers_count

    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    author = post.author
    post_list = author.posts
    post_count = post_list.count()
    self_comments = post.comments.all()
    comment_form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'post_count': post_count,
        'post_list': post_list,
        'author': author,
        'form': comment_form,
        'comments': self_comments

    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        request.FILES or None
    )
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', request.user.username)

    context = {
        'form': form
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    edit_post = get_object_or_404(Post, id=post_id)
    if request.user != edit_post.author:
        return redirect('posts:post_detail', post_id=edit_post.id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=edit_post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', edit_post.id)
    context = {
        'form': form,
        'is_edit': True
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    # информация о текущем пользователе доступна в переменной request.user
    following_posts = Post.objects.all().filter(
        author__following__user=request.user
    )
    template = 'posts/follow.html'
    page_obj = pagination(request, following_posts, PAGE_COEF)
    context = {
        'page_obj': page_obj
    }

    return render(request, template, context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    template = reverse('posts:profile', args=((username,)))
    user = request.user
    author = get_object_or_404(User, username=username)
    exist = Follow.objects.filter(author=author, user=user).exists()
    if user != author and not exist:
        Follow.objects.create(user=user, author=author)
    return redirect(template)


@login_required
def profile_unfollow(request, username):
    # Дизлайк, отписка
    template = reverse('posts:profile', args=((username,)))
    user = request.user
    author = get_object_or_404(User, username=username)
    follow_obj = Follow.objects.filter(user=user, author=author)
    follow_obj.delete()
    return redirect(template)

yatube/templates/posts/create_post.html
{% extends "base.html" %}

{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Добавить запись
          {% endif %}            
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
        
          <form method="post" enctype="multipart/form-data">
            {% load user_filters %}
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field|addclass:"form-control" }}
                {% if field.help_text %}
                  <small 
                    id="{{ field.id_for_label }}-help" 
                    class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}


            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %} 
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}



{% block title %}    
Лента подписок
{% endblock %}

  
  {% block content %}  
    <!-- класс py-5 создает отступы сверху и снизу блока -->
    <div class="container py-5">
      {% include 'posts/includes/switcher.html' %}             
      <h1>Лента подписок</h1> <br>
      <article>      
        {% include 'posts/includes/post_list.html' %}
        {% include 'posts/includes/paginator.html' %}        
      </article>  
      <!-- под последним постом нет линии -->
    </div> 
  
  {% endblock %} 
    

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
        
{% block title %}   
  {{ group.title }}
{% endblock %}

{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in page_obj %}                              
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }} <a href = "{% url 'posts:profile' post.author %}"> Все посты пользователя</a> <br>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}  
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href = "{% url 'posts:post_detail' post.id %}"> Подробнее </a> <br>
      {% if post.group.slug %}
        <a href = "{% url 'posts:group_list' post.group.slug %}"> Другие записи группы  "{{ post.group.title }}" </a>
      {% endif %}
      {% if not forloop.last %} <hr> {% endif %}
    {% endfor %}   
    <!-- под последним постом нет линии -->
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}
    
  

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}    
Это главная страница проекта Yatube
{% endblock %}

  
{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->    
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}       
    <h1>Последние обновления на сайте</h1> <br>
    <article>
    {% load cache %}
    {% cache 20 index_page page_obj.number %}      
      {% include 'posts/includes/post_list.html' %}   
    {% endcache %}     
    {% include 'posts/includes/paginator.html' %}
       
    </article>  
    <!-- под последним постом нет линии -->
  </div> 

{% endblock %} 
    

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block title %}  
{{post.text|truncatechars:30 }} 
{% endblock %}

{% block content %}
<div class="row container py-5" >
  <aside class="col-12 col-md-3 ">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">    
        Дата публикации: {{ post.pub_date|date:"d E Y" }}  
      </li>
      {% if post.group.slug %}
      <li class="list-group-item">
      Группа  {{ post.group.title }} <br>
      <a href = "{% url 'posts:group_list' post.group.slug %}"> все записи группы </a>
      {% endif %}
      </li>
      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>        
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора: {{ post_count }}
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' author.username %}">
          все посты пользователя 
        </a>
      </li>
    </ul>
  </aside>  
  <article class="col-12 col-md-9 container py-5">  
    {% thumbnail post.image "960x650" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}     
    <p> {{ post.text }} </p> <br>
    {% if post.author == request.user %}
      <form action="{% url 'posts:post_edit' post.id %}">
        <button class="btn btn-primary">        
        Редактировать запись         
        </button>  
      </form>      
    {% endif %}
    <!-- Форма добавления комментария -->  
    {% include 'posts/includes/comments.html' %}
  </article>  
</div>

{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Профайл пользователя {{ author.username }}
{% endblock %}

{% block content %} 
    
  <div class="container py-5">        
    <h1>Все посты пользователя  {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ post_count }}  </h3>
    <h3>Подписчиков: {{ followers_count }}  </h3>  
  <div class="mb-5">
    {% if user != author and user.is_authenticated %}
      {% if following %}
        <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
        Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
        Подписаться
        </a>
      {% endif %}
    {% endif %}
  </div>   
    <article>
        {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}  
          </li>
        </ul>
        <br>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p> {{ post.text }} <br>
          <br>
          <br>              
        <a href="{% url 'posts:post_detail' post.id %}">Подробная информация </a><br>
        {% if post.group.slug %}
          <a href = "{% url 'posts:group_list' post.group.slug %}"> Другие записи группы </a>
        {% endif %}
        {% if not forloop.last %} <hr> {% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      
    </article>       
            
    
  </div>
{% endblock %}
    